"""add alt_text & detected_labels on Photo

Revision ID: 6264ab40f459
Revises: 
Create Date: 2025-09-19 12:41:08.481576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6264ab40f459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('detected_labels', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_column('detected_labels')
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###
